# Generated by Django 3.0 on 2019-12-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_correcao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='qt_passageiros',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
